
redis: &redis
  adapter: redis
  url: ENV["REDIS_URL"] || redis://localhost:6379/1

development: 
  <<: *redis
  channel_prefix: app_dev
test: 
  <<: *redis

production:
  <<: *redis
  channel_prefix: app_production
