
redis: &redis
  async

development: 
  <<: *redis
  channel_prefix: app_dev
test: 
  <<: *redis

production:
  adapter: redis
  #url: redis://localhost:6379/1
  url: redis://h:pfb0f4a6a4f6dc734978028c21ca4fe98bc468389ae3f61e0c07097229e324a0d@ec2-18-205-186-65.compute-1.amazonaws.com:18169
  channel_prefix: deploy_app_to_heroku_production
