
redis: &redis
  async

development: 
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: app_dev
test: 
  <<: *redis

production:
  adapter: redis
  #url: redis://localhost:6379/1
  url: redis://redistogo:5f89f636a92769b8734d734b0e280f56@spinyfin.redistogo.com:11014/
  channel_prefix: deploy_app_to_heroku_production
  :inline: true
  :timeout: 1