
redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: 
  <<: *redis
  channel_prefix: app_dev
test: 
  <<: *redis

production:
  adapter: redis
  url:  redis://redistogo:8fdc0523a872f3f4bc8861c1946f9f8d@spinyfin.redistogo.com:10925/
 
