
redis: &redis
  async

development: 
  <<: *redis
  channel_prefix: app_dev
test: 
  <<: *redis

production:
  adapter: redis
  #url: redis://localhost:6379/1
  url: <%= ENV['REDISPROD_URL'] %>
  channel_prefix: deploy_app_to_heroku_production
